### ISSUE TITLE
desktop file文件里的version字段不应存在

### ISSUE THREAD

**Issue by pugaizai** [wgh136/pixes#10]
debian/gui/xxx.desktop

https://specifications.freedesktop.org/desktop-entry-spec/latest/recognized-keys.html

文件里的Version字段指的是desktop file的版本，不是应用软件的版本

**Comment by pugaizai** [comment]
venera那边也是这个问题

**Comment by wgh136** [comment]
已更新release
venera的下个版本发布时修复
